[package]
name = "particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ggez = "0.9.0-rc0"
nalgebra = "0.32.2"
rand = "0.8.5"
getset = "0.1.2"
